{{- if .Values.global.clusterd.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "clusterd.fullname" . }}
  labels:
    {{- include "clusterd.labels" . | nindent 4 }}
data:
  clusterd.yaml: |
    version: "1.1"
    listener:
      port: {{ .Values.global.clusterd.service.port }}
    pki:
      certificate:
        path: /etc/halon/tls/controlsocket-server/tls.crt
      privatekey:
        path: /etc/halon/tls/controlsocket-server/tls.key
      clientcerts:
        - path: /etc/halon/tls/smtpd-controlsocket-client-crt/tls.crt
    environment:
      privdrop:
        user: clusterd
        group: clusterd
{{- end }}
